### ISSUE TITLE
How would I add this to an OCI image?

### ISSUE THREAD

**Issue by Waffleophagus** [DHowett/framework-laptop-kmod#11]
Heya! So I am really excited about this work! Just got my 16 and am trying to get this installed. But I am running Universal Blue ( https://ublue.it ) using Blue Build right now ( https://blue-build.org/ ) and I've been banging my head against the wall for a few hours so far attempting to install the module during the image build process and have gotten nowhere. I did open an issue on Ublue's repo because they have a streamlined way to add kmods ( https://github.com/ublue-os/akmods/issues/137 ), but figure I'd attack this problem from multiple angles and ask here as well? During the build process it appears that the current directory for the building of modules doesn't exist? `/usr/src/kernels/6.7.6-200.fc39.x86_64` which from where I am sitting, is required by your make script. I'll happily assist in any way I can in this and would happily make a PR back even if its documentation if we can figure it out! 

Thanks,
Matt

P.S. If you wanna chat in the Framework discord, I'm Waffleophagus there as well.

**Comment by DHowett** [comment]
I suspect that this has been resolved, since it may be part of Bazzite or a uBlue build at the moment! Thanks for all the work on this one 🙂
