### ISSUE TITLE
cros_ec_lpcs: No such device

### ISSUE THREAD

**Issue by MoralCode** [DHowett/framework-laptop-kmod#3]
Kernel: 5.15.0-89-generic
Framework 13 11th Gen (i5-1135G7)

The README and `modprobe --show-depends  framework_laptop` show that this module depends on `cros_ec` and `cros_ec_lpcs`, however on my system `cros_ec_lpcs` is not loaded, and trying to load it with `insmod` gives an error: `cros_ec_lpcs.ko: No such device`.

Am i missing the requisite hardware for this module to work? it sorta sounded like all intel FW 13" laptops had the MEC chip mentioned [here](https://community.frame.work/t/what-ec-is-used/38574)

**Comment by DHowett** [comment]
I'm not certain whether 5.15 shipped with the patch to add support for the Framework Laptop to `cros_ec_lpcs`. I'm away from my laptop at the moment and unfortunately can't check. 🙂

**Comment by MoralCode** [comment]
Ah ok, so [your testing on 5.10](https://community.frame.work/t/responded-controlling-the-keyboard-backlight-through-sys/27483/7) was done on a modified 5.10 with the FW-specific patch applied?

**Comment by DHowett** [comment]
> Ah ok, so [your testing on 5.10](https://community.frame.work/t/responded-controlling-the-keyboard-backlight-through-sys/27483/7) was done on a modified 5.10 with the FW-specific patch applied?

Unfortunately, I think that must have been what I'd done. Sorry about that. 🙁
