### ISSUE TITLE
Commit upstream?

### ISSUE THREAD

**Issue by CappyT** [DHowett/framework-laptop-kmod#8]
As the title says, is it possible (if not done already) to commit this into the upstream Linux kernel?
I don't know the rules for submitting this kind of driver.

**Comment by DHowett** [comment]
That's the eventual goal! When this driver is of a quality level that would be acceptable for the kernel, I'll submit it. :)

**Comment by DHowett** [comment]
@t-8ch's recent work to add cros_ec kblight, hwmon and charge control support to the kernel has largely superseded the need for this driver.

I'm happy for upstreaming no longer to be a target for this project unless it truly does grow some Framework-specific support that can't be fulfilled by other drivers.

**Comment by rmeissn** [comment]
Currently, this is the case for battery charge controls. See: https://community.frame.work/t/request-testing-of-linux-drivers-on-all-laptop-models/51283/22?u=roy_meissner
